# Generated by Django 5.2.4 on 2025-08-12 23:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='vote',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Opaque client identifier used to prevent duplicate anonymous votes.', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('voter__isnull', False)), fields=('election', 'voter'), name='uniq_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(condition=models.Q(('device_fingerprint__isnull', False)), fields=('election', 'device_fingerprint'), name='uniq_vote_per_device'),
        ),
    ]
